# Generated by Django 4.0.5 on 2022-06-15 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_created_date_remove_post_published_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post2',
            new_name='P2',
        ),
    ]
